# Generated by Django 3.1.7 on 2021-03-19 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=20)),
                ('task_text', models.CharField(max_length=100)),
                ('time_of_ending', models.DateField()),
                ('task_status', models.CharField(choices=[('NOT_ACCEPTED', 'Not accepted'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='NOT_ACCEPTED', max_length=20)),
                ('task_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.boards')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boards', models.ManyToManyField(to='firstapp.Boards')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
