# Generated by Django 3.1.6 on 2021-02-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=20)),
                ('task_text', models.CharField(max_length=100)),
                ('time_of_ending', models.DateField()),
            ],
        ),
    ]
