# Generated by Django 3.1.7 on 2021-03-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boards',
            field=models.ManyToManyField(to='firstapp.Boards'),
        ),
    ]
